language: bash

<<<<<<< HEAD
os:
  - linux
  # OS X tests are taking too long to run :(
  # - osx

# Prepare the environment
addons:
  apt:
    packages:
      - bc
      - links
=======
>>>>>>> origin/aureliojargas-testing
before_install:
  - url_base="https://raw.githubusercontent.com/aureliojargas/clitest"
  - curl -sOL "${url_base}/master/clitest"
  - chmod +x clitest
  - mv clitest testador

script:
<<<<<<< HEAD
  - if test "$TRAVIS_OS_NAME" = osx;   then cd testador && ./run; fi
  - if test "$TRAVIS_OS_NAME" = linux; then cd testador && ./run $(ls -1 zz*.sh | grep -xv zzlinux.sh); fi
  # Exclude zzlinux tests in Linux (see https://github.com/funcoeszz/funcoeszz/issues/355) 
=======
  - cd testador && ./run zzcores.sh
>>>>>>> origin/aureliojargas-testing

notifications:
  email: false
